TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += Command.db
DB += CommandReg.db
DB += ADC.db
DB += User.db
DB += MatrixCoef.db
include $(TOP)/configure/RULES
