void v20xv20(float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float);

void Layer1_20x20(float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,

		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float *, float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,
		float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float,float);
